# Generated by Django 4.0 on 2022-05-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_faq"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FAQ",
        ),
    ]
