# Generated by Django 3.2.13 on 2022-05-07 10:22

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_delete_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("skill_point", models.PositiveBigIntegerField(default=0)),
                ("referral", models.PositiveSmallIntegerField(default=0)),
                ("completed_lesson", models.PositiveSmallIntegerField(default=0)),
                ("completed_course", models.PositiveSmallIntegerField(default=0)),
                ("total_earning", models.PositiveBigIntegerField(default=0)),
                (
                    "user",
                    auto_prefetch.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__first_name", "user__last_name"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
