# Generated by Django 3.2.13 on 2022-05-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_userstatistic"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstatistic",
            name="wallet_amount",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
