# Generated by Django 3.2.13 on 2022-05-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_userstatistic_wallet_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglist",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="mailinglistcategory",
            name="name",
            field=models.CharField(
                choices=[("coming_soon", "Coming soon"), ("newsletter", "Newsletter")],
                default="newsletter",
                max_length=20,
                unique=True,
            ),
        ),
    ]
