# Generated by Django 3.2.13 on 2022-05-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_auto_20220510_1242"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglist",
            name="email",
            field=models.EmailField(max_length=30),
        ),
    ]
