# Generated by Django 4.0 on 2022-05-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_lessonpayment_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonpayment",
            name="amount_fee",
            field=models.CharField(default="0", max_length=15),
        ),
        migrations.AddField(
            model_name="lessonpayment",
            name="amount_gross",
            field=models.CharField(default="0", max_length=15),
        ),
        migrations.AddField(
            model_name="lessonpayment",
            name="amount_net",
            field=models.CharField(default="0", max_length=15),
        ),
    ]
