# Generated by Django 4.0 on 2022-05-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment",
         "0003_lessonpayment_amount_fee_lessonpayment_amount_gross_and_more",
         ),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonpayment",
            name="name_on_card",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
