# Generated by Django 4.0 on 2022-05-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_remove_lessonpayment_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonpayment",
            name="paid_tutor",
            field=models.BooleanField(default=False),
        ),
    ]
