# Generated by Django 4.0 on 2022-05-04 12:24

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutor",
         "0003_rename_list_of_subject_you_teach_tutorrequest_name_of_subject_you_teach",
         ),
        ("promotion",
         "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorpromotion",
            name="tutor",
            field=auto_prefetch.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="tutor.tutor"
            ),
        ),
    ]
