# Generated by Django 4.0 on 2022-05-03 00:33

import datetime

import auto_prefetch
import django.db.models.deletion
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        ("lesson", "0007_alter_review_lesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="booked_by",
        ),
        migrations.AddField(
            model_name="lesson",
            name="created_by",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by",
                to="home.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="lesson",
            field=auto_prefetch.OneToOneField(
                blank=True,
                limit_choices_to={
                    "start_datetime__lte": datetime.datetime(
                        2022, 5, 3, 0, 33, 17, 288494, tzinfo=utc
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lesson.lesson",
            ),
        ),
    ]
