# Generated by Django 4.0 on 2022-05-03 11:09

import datetime

import auto_prefetch
import django.db.models.deletion
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0008_remove_lesson_booked_by_lesson_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="lesson",
            field=auto_prefetch.OneToOneField(
                blank=True,
                limit_choices_to={
                    "start_datetime__lte": datetime.datetime(
                        2022, 5, 3, 11, 9, 59, 280684, tzinfo=utc
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lesson.lesson",
            ),
        ),
    ]
