# Generated by Django 4.0 on 2022-05-03 12:40

import uuid

import auto_prefetch
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0011_alter_review_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="lesson",
            field=auto_prefetch.OneToOneField(
                blank=True,
                limit_choices_to={
                    "start_datetime__lte": django.utils.timezone.now},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lesson.lesson",
            ),
        ),
    ]
