# Generated by Django 4.0 on 2022-05-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0012_alter_lesson_uuid_alter_review_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="meeting_link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
