# Generated by Django 4.0.6 on 2022-07-30 19:01

import auto_prefetch
import datetime
from django.db import migrations
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0020_alter_review_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='lesson',
            field=auto_prefetch.OneToOneField(blank=True, limit_choices_to={'start_datetime__lte': datetime.datetime(2022, 7, 30, 19, 1, 2, 221744, tzinfo=utc)}, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson'),
        ),
    ]
