# Generated by Django 4.0 on 2022-05-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0002_alter_tutorrequest_list_of_subject_you_teach"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutorrequest",
            old_name="list_of_subject_you_teach",
            new_name="name_of_subject_you_teach",
        ),
    ]
