# Generated by Django 4.0 on 2022-05-04 12:15

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_delete_faq"),
        ("blog", "0003_alter_blog_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=auto_prefetch.ForeignKey(
                limit_choices_to={"is_staff": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="home.customuser",
            ),
        ),
    ]
