# Generated by Django 4.0 on 2022-05-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_category_blog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
